let productos = [
    { "id": "21", "nombre": "Galletitas dulces envasadas sin relleno", "peso": "150 g", "categoria_id": "3" },
    { "id": "22", "nombre": "Galletitas dulces envasadas sin relleno", "peso": "150 g", "categoria_id": "3" },
    { "id": "23", "nombre": "Galletitas de agua envasadas", "peso": "250 g", "categoria_id": "3" },
    { "id": "24", "nombre": "Galletitas de agua envasadas", "peso": "250 g", "categoria_id": "3" },
    { "id": "25", "nombre": "Galletitas de agua envasadas", "peso": "250 g", "categoria_id": "3" },
    { "id": "26", "nombre": "Galletitas de agua envasadas", "peso": "250 g", "categoria_id": "3" },
    { "id": "27", "nombre": "Harina de trigo común 000", "peso": "1 kg", "categoria_id": "3" },
    { "id": "28", "nombre": "Harina de trigo común 000", "peso": "1 kg", "categoria_id": "3" },
    { "id": "29", "nombre": "Harina de trigo común 000", "peso": "1 kg", "categoria_id": "3" },
    { "id": "30", "nombre": "Arroz blanco simple", "peso": "1 kg", "categoria_id": "3" },
    { "id": "31", "nombre": "Arroz blanco simple", "peso": "1 kg", "categoria_id": "3" },
    { "id": "32", "nombre": "Arroz blanco simple", "peso": "1 kg", "categoria_id": "3" },
    { "id": "33", "nombre": "Fideos secos tipo guisero", "peso": "500 g", "categoria_id": "3" },
    { "id": "34", "nombre": "Fideos secos tipo guisero", "peso": "500 g", "categoria_id": "3" },
    { "id": "35", "nombre": "Hamburguesas congeladas", "peso": "Env. 4 u", "categoria_id": "3" },
    { "id": "36", "nombre": "Hamburguesas congeladas", "peso": "Env. 4 u", "categoria_id": "3" },
    { "id": "37", "nombre": "Salchicha tipo viena", "peso": "Env. 6 u", "categoria_id": "3" },
    { "id": "38", "nombre": "Salchicha tipo viena", "peso": "Env. 6 u", "categoria_id": "3" },
    { "id": "39", "nombre": "Aceite de girasol", "peso": "1,5 litros", "categoria_id": "3" },
    { "id": "40", "nombre": "Aceite de girasol", "peso": "1,5 litros", "categoria_id": "3" },
    { "id": "41", "nombre": "Huevos de gallina", "peso": "Docena", "categoria_id": "3" },
    { "id": "42", "nombre": "Huevos de gallina", "peso": "Docena", "categoria_id": "3" },
    { "id": "43", "nombre": "Tomate entero en conserva", "peso": "Lata 230 g", "categoria_id": "3" },
    { "id": "44", "nombre": "Tomate entero en conserva", "peso": "Lata 230 g", "categoria_id": "3" },
    { "id": "45", "nombre": "Arvejas secas remojadas", "peso": "Lata 220 g", "categoria_id": "3" },
    { "id": "46", "nombre": "Arvejas secas remojadas", "peso": "Lata 22o g", "categoria_id": "3" },
    { "id": "47", "nombre": "Azúcar", "peso": "1 kg", "categoria_id": "3" },
    { "id": "48", "nombre": "Azúcar", "peso": "1 kg", "categoria_id": "3" },
    { "id": "49", "nombre": "Sal fina", "peso": "500 g", "categoria_id": "3" },
    { "id": "50", "nombre": "Sal fina", "peso": "500 g", "categoria_id": "3" },
    { "id": "51", "nombre": "Polvo para flan", "peso": "8 porciones", "categoria_id": "3" },
    { "id": "52", "nombre": "Polvo para flan", "peso": "8 porciones", "categoria_id": "3" },
    { "id": "53", "nombre": "Café molido", "peso": "500 g", "categoria_id": "3" },
    { "id": "54", "nombre": "Café molido", "peso": "500 g", "categoria_id": "3" },
    { "id": "55", "nombre": "Yerba mate", "peso": "500 g", "categoria_id": "3" },
    { "id": "56", "nombre": "Yerba mate", "peso": "500 g", "categoria_id": "3" },
    { "id": "57", "nombre": "Gaseosa base cola", "peso": "1,5 litros", "categoria_id": "4" },
    { "id": "58", "nombre": "Gaseosa base cola", "peso": "1,5 litros", "categoria_id": "4" },
    { "id": "59", "nombre": "Agua sin gas", "peso": "1,5 litros", "categoria_id": "4" },
    { "id": "60", "nombre": "Agua sin gas", "peso": "1,5 litros", "categoria_id": "4" },
    { "id": "61", "nombre": "Cerveza en botella", "peso": "1 litro", "categoria_id": "4" },
    { "id": "62", "nombre": "Cerveza en botella", "peso": "1 litro", "categoria_id": "4" },
    { "id": "63", "nombre": "Vino común", "peso": "1 litro", "categoria_id": "4" },
    { "id": "64", "nombre": "Vino común", "peso": "1 litro", "categoria_id": "4" },
    { "id": "65", "nombre": "Asado", "peso": "Kg", "categoria_id": "5" },
    { "id": "66", "nombre": "Carne picada común", "peso": "Kg", "categoria_id": "5" },
    { "id": "67", "nombre": "Paleta", "peso": "Kg", "categoria_id": "5" },
    { "id": "68", "nombre": "Cuadril", "peso": "Kg", "categoria_id": "5" },
    { "id": "69", "nombre": "Nalga", "peso": "Kg", "categoria_id": "5" },
    { "id": "70", "nombre": "Pollo entero", "peso": "Kg", "categoria_id": "5" },
    { "id": "71", "nombre": "Asado", "peso": "Kg", "categoria_id": "5" },
    { "id": "72", "nombre": "Carne picada común", "peso": "Kg", "categoria_id": "5" },
    { "id": "73", "nombre": "Paleta", "peso": "Kg", "categoria_id": "5" },
    { "id": "74", "nombre": "Cuadril", "peso": "Kg", "categoria_id": "5" },
    { "id": "75", "nombre": "Pollo entero", "peso": "Kg", "categoria_id": "5" },
    { "id": "76", "nombre": "Nalga", "peso": "Kg", "categoria_id": "5" },
    { "id": "77", "nombre": "Jamón cocido", "peso": "Kg", "categoria_id": "6" },
    { "id": "78", "nombre": "Jamón cocido", "peso": "Kg", "categoria_id": "6" },
    { "id": "79", "nombre": "Salchichón", "peso": "Kg", "categoria_id": "6" },
    { "id": "80", "nombre": "Salchichón", "peso": "Kg", "categoria_id": "6" },
    { "id": "81", "nombre": "Salame", "peso": "Kg", "categoria_id": "6" },
    { "id": "82", "nombre": "Salame", "peso": "Kg", "categoria_id": "6" },
    { "id": "83", "nombre": "Queso cremoso", "peso": "Kg", "categoria_id": "6" },
    { "id": "84", "nombre": "Queso cremoso", "peso": "1Kg", "categoria_id": "6" },
    { "id": "85", "nombre": "Queso cremoso", "peso": "Kg", "categoria_id": "6" },
    { "id": "86", "nombre": "Queso sardo", "peso": "Kg", "categoria_id": "6" },
    { "id": "87", "nombre": "Queso sardo", "peso": "Kg", "categoria_id": "6" },
    { "id": "88", "nombre": "Manzana deliciosa", "peso": "Kg", "categoria_id": "7" },
    { "id": "89", "nombre": "Manzana deliciosa", "peso": "Kg", "categoria_id": "7" },
    { "id": "90", "nombre": "Limón", "peso": "Kg", "categoria_id": "7" },
    { "id": "91", "nombre": "Limón", "peso": "Kg", "categoria_id": "7" },
    { "id": "92", "nombre": "Naranja", "peso": "Kg", "categoria_id": "7" },
    { "id": "93", "nombre": "Naranja", "peso": "Kg", "categoria_id": "7" },
    { "id": "94", "nombre": "Banana", "peso": "Kg", "categoria_id": "7" },
    { "id": "95", "nombre": "Banana", "peso": "Kg", "categoria_id": "7" },
    { "id": "96", "nombre": "Batata", "peso": "Kg", "categoria_id": "7" },
    { "id": "97", "nombre": "Batata", "peso": "Kg", "categoria_id": "7" },
    { "id": "98", "nombre": "Papa", "peso": "Kg", "categoria_id": "7" },
    { "id": "99", "nombre": "Papa", "peso": "Kg", "categoria_id": "7" },
    { "id": "100", "nombre": "Cebolla", "peso": "Kg", "categoria_id": "7" },
    { "id": "101", "nombre": "Cebolla", "peso": "Kg", "categoria_id": "7" },
    { "id": "102", "nombre": "Lechuga", "peso": "Kg", "categoria_id": "7" },
    { "id": "103", "nombre": "Lechuga", "peso": "Kg", "categoria_id": "7" },
    { "id": "104", "nombre": "Tomate redondo", "peso": "Kg", "categoria_id": "7" },
    { "id": "105", "nombre": "Tomate redondo", "peso": "Kg", "categoria_id": "7" },
    { "id": "106", "nombre": "Zapallo anco", "peso": "Kg", "categoria_id": "7" },
    { "id": "107", "nombre": "Zapallo anco", "peso": "Kg", "categoria_id": "7" },
    { "id": "108", "nombre": "Leche fresca entera en sachet", "peso": "Litro", "categoria_id": "8" },
    { "id": "109", "nombre": "Leche fresca entera en sachet", "peso": "Litro", "categoria_id": "8" },
    { "id": "110", "nombre": "Leche en polvo entera", "peso": "800 g", "categoria_id": "8" },
    { "id": "111", "nombre": "Leche en polvo entera", "peso": "800 g", "categoria_id": "8" },
    { "id": "112", "nombre": "Manteca", "peso": "200 g", "categoria_id": "8" },
    { "id": "113", "nombre": "Manteca", "peso": "200 g", "categoria_id": "8" },
    { "id": "114", "nombre": "Yogur firme", "peso": "195 cc", "categoria_id": "8" },
    { "id": "115", "nombre": "Yogur firme", "peso": "195 cc", "categoria_id": "8" },
    { "id": "116", "nombre": "Dulce de leche", "peso": "400 g", "categoria_id": "8" },
    { "id": "117", "nombre": "Dulce de leche", "peso": "400 g", "categoria_id": "8" },
    { "id": "118", "nombre": "Pan francés tipo flauta", "peso": "kg", "categoria_id": "9" },
    { "id": "119", "nombre": "Pan de mesa", "peso": "390 g", "categoria_id": "9" },
    { "id": "120", "nombre": "Pan de mesa", "peso": "390 g", "categoria_id": "9" },
    { "id": "121", "nombre": "Algodón", "peso": "100 g", "categoria_id": "10" },
    { "id": "122", "nombre": "Algodón", "peso": "100 g", "categoria_id": "10" },
    { "id": "123", "nombre": "Champú", "peso": "400 cc", "categoria_id": "11" },
    { "id": "124", "nombre": "Champú", "peso": "400 cc", "categoria_id": "11" },
    { "id": "125", "nombre": "Desodorante", "peso": "150 cc", "categoria_id": "11" },
    { "id": "126", "nombre": "Desodorante", "peso": "150 cc", "categoria_id": "11" },
    { "id": "127", "nombre": "Jabón de tocador", "peso": "125 g", "categoria_id": "11" },
    { "id": "128", "nombre": "Jabón de tocador", "peso": "125 g", "categoria_id": "11" },
    { "id": "129", "nombre": "Pañales descartables", "peso": "10 u", "categoria_id": "11" },
    { "id": "130", "nombre": "Pañales descartables", "peso": "10 u", "categoria_id": "11" },
    { "id": "131", "nombre": "Detergente líquido", "peso": "750 cc", "categoria_id": "12" },
    { "id": "132", "nombre": "Detergente líquido", "peso": "750 cc", "categoria_id": "12" },
    { "id": "133", "nombre": "Jabón en pan", "peso": "200 g", "categoria_id": "12" },
    { "id": "134", "nombre": "Jabón en pan", "peso": "200 g", "categoria_id": "12" },
    { "id": "135", "nombre": "Jabón en polvo para ropa", "peso": "800 g", "categoria_id": "12" },
    { "id": "136", "nombre": "Jabón en polvo para ropa", "peso": "800 g", "categoria_id": "12" },
    { "id": "137", "nombre": "Lavandina", "peso": "1.000 cc", "categoria_id": "12" },
    { "id": "138", "nombre": "Lavandina", "peso": "1.000 cc", "categoria_id": "12" }
]

// post processing
productos.forEach(element => {
    element.displayName = element.nombre + "(" + element.peso + ")"
});


export default productos;